version: "3.8"

# Networks
networks:
  queue_orchestrator:
    external: true

services:

  # Notifications
  notifications-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notifications
    environment:
      APP_PORT: 80
    ports:
      - '2004:80'
    expose:
      - "80"
    volumes:
      - ./notification-service/:/app/
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:80/health/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - queue_orchestrator
    restart: always
    command: sh -c "gunicorn -b :80 main:main_app --workers 1 --threads 8 --timeout 0 --log-level debug --reload"

