version: "3"

networks:
  micro_network:
    external: true

services:

  # Services
  dbservices:
    image: postgres
    container_name: dbservices
    environment:
      POSTGRES_DB: services
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5400:5432'
    expose:
      - "5432"
    networks:
      - micro_network
    restart: always

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      APP_PORT: 2000
    ports:
      - '2000:2000'
    expose:
      - "2000"
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./src:/app/src
      - ./main.py:/app/main.py
    depends_on:
      - dbservices
    networks:
      - micro_network
    restart: always
    command: >
      sh -c "flask db migrate && flask db upgrade && gunicorn -b :80 main:gunicorn_app"
    #command: >
    #      sh -c "python main.py"

