version: "3"

networks:
  micro_network:
    external: true

services:

  # Logs
  dblogs:
    image: postgres
    container_name: dblogs
    environment:
      POSTGRES_DB: log
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5404:5432'
    expose:
      - "5432"
    networks:
      - micro_network
    restart: always

  logs-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logs
    environment:
      APP_PORT: 2003
    ports:
      - '2003:2003'
    expose:
      - "2003"
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
      - ./src:/app/src
      - ./main.py:/app/main.py
    depends_on:
      - dbautomations
    networks:
      - micro_network
    restart: always
    #command: >
    #  sh -c "flask db migrate && flask db upgrade && gunicorn -b :80 main:gunicorn_app"
    command: >
          sh -c "python main.py"

