version: "3.8"


# Networks
networks:
  queue_orchestrator:
    external: true

# Volumes
volumes:
  # DbUsers
  dbusers_data:


services:

  # Auth
  auth-db:
    image: postgres:alpine
    container_name: dbusers
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5402:5432'
    expose:
      - "5432"
    networks:
      - queue_orchestrator
    depends_on:
      gateway:
        condition: service_healthy
    volumes:
      - dbusers_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "psql", "user", "-U", "admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth
    environment:
      APP_PORT: 80
    ports:
      - '2001:80'
    expose:
      - "80"
    volumes:
      - ./auth-service/:/app/
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:80/health/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - queue_orchestrator
    restart: on-failure
    command: sh -c "gunicorn -b :80 main:main_app --workers 1 --threads 8 --timeout 0 --log-level debug --reload"
